### ISSUE TITLE
Issue with capitalization of todos.js module

### ISSUE THREAD

**Issue by oppodeldoc** [heygrady/react-redux-notes#2]
Ran into this when doing the tutorial and following all naming specified here then running an `npm start dev`:

```
WARNING in ./src/routes/Todos/modules/todos.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./src/routes/Todos/modules/Todos.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

Turned up this issue where Webpack gets mad when you have something like `src/routes/Todos/modules/todos.js` and then try to import or require it like `import { addTodo } from '../modules/Todos'` and `const reducer = require('./modules/todos').default` (note the inconsistency in capitalizations)

Not sure if this is simply a typo but It brought up a question for me. I just fixed it by changing all the imports to be consistently lowercase but are we supposed to be capitalizing module file names? All the containers and components are capitalized, but the todos.js module isn't. Guidance here would be helpful, thanks!

**Comment by heygrady** [comment]
Typo. Will fix

**Comment by heygrady** [comment]
WRT filename capitalization...

It's good practice in React to [use PascalCase for components](https://github.com/airbnb/javascript/tree/master/react#naming). However, there isn't really a consensus between [the different file naming styles](https://news.ycombinator.com/item?id=8659878) for other files. I would suggest going with camelCase for non-components. I don't have any reasoning to support that at this point.

FWIW, [node modules typically use hyphen-case](https://www.quora.com/Why-does-people-suggest-use-dash-but-not-underscore-in-javascript-file-name). There are [issues on Windows](https://github.com/nodejs/node-v0.x-archive/issues/6000) when using capitalization for filenames (because [Windows is case-insensitive](http://superuser.com/questions/165975/are-all-versions-of-windows-case-insensitive)). Historically people have [avoided using capitalization in filenames](http://www.thesitewizard.com/webdesign/create-good-filenames.shtml) for that reason. These days avoiding capitalization in a file name is probably as important as [limiting it to 8 characters](https://en.wikipedia.org/wiki/8.3_filename).

File naming is one of those issues like [2-space tabs](http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e) or [dropping semi-colons](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) where the answer is totally subjective. In the past I have always recommended trying to make your code look like someone else's and hope no one complains.
