### ISSUE TITLE
Typo or clarification or both in section on edits to createStore.js in sagas notes

### ISSUE THREAD

**Issue by oppodeldoc** [heygrady/react-redux-notes#3]
@heygrady  I was getting a couple errors on the front end after going through the sagas notes, [both from the same snippet](https://github.com/heygrady/react-redux-notes/blob/master/redux-sagas-todos.md#srcstorecreatestorejs):

```
// we're already importing our reducers
import reducers from './reducers'
```

This is slightly different from what's actually being imported in the actual file, the line looks like:
`import makeRootReducer from './reducers'`

The bigger issue is this line, which breaks the app:
`let middleware = applyMiddleware(thunk, routerMiddleware(history), sagaMiddleware)`

I'm still learning a lot about sagas so I might be wrong but I **think** (thunk?) this should be:
`const middleware = [thunk, routerMiddleware(history), sagaMiddleware]`

Using that and leaving the rest of the file as-is other than adding `sagaMiddleware.run(rootSaga)` works just fine. Thanks so much for writing about all this, I'm learning a ton.

**Comment by heygrady** [comment]
Oh, thank you. You found a line that's been upgraded since I first wrote this. In my demo files that line looks different than the current version of react-redux-starter-kit. I'll upgrade my local and fix this up.

I might consider linking to a versioned file but I usually prefer to keep the notes current.
